extends Object
class_name ScenarioData

const Terrain = Globals.Terrain

static var game = {
	"name": "ClassicExplorer",
	"player_piece_set": {
		"town": 10,
		"city": 4,
		"sea_city": 0,
		"road": 15,
		"ship": 0,
		"wall": 0,
		"knight_1": 0,
		"knight_2": 0,
		"knight_3": 0,
	},
	"map": [
		# hex-x, hex-y, deck
		[-3, -3, "sea"],
		[-3, -2, "sea"],
		[-3, -1, "sea"],
		[-3, +0, "sea"],
		[-2, -3, "sea"],
		[-2, -2, "land"],
		[-2, -1, "land"],
		[-2, +0, "land"],
		[-2, +1, "sea"],
		[-1, -3, "sea"],
		[-1, -2, "land"],
		[-1, -1, "land"],
		[-1, +0, "land"],
		[-1, +1, "land"],
		[-1, +2, "sea"],
		[+0, -3, "sea"],
		[+0, -2, "land"],
		[+0, -1, "land"],
		[+0, +0, "land"],
		[+0, +1, "land"],
		[+0, +2, "land"],
		[+0, +3, "sea"],
		[+1, -2, "sea"],
		[+1, -1, "land"],
		[+1, +0, "land"],
		[+1, +1, "land"],
		[+1, +2, "land"],
		[+1, +3, "sea"],
		[+2, -1, "sea"],
		[+2, +0, "land"],
		[+2, +1, "land"],
		[+2, +2, "land"],
		[+2, +3, "sea"],
		[+3, +0, "sea"],
		[+3, +1, "sea"],
		[+3, +2, "sea"],
		[+3, +3, "sea"],
		[+4, +0, "sea"],
		[+4, +1, "newworld"],
		[+4, +2, "newworld"],
		[+4, +3, "newworld"],
		[+4, +4, "sea"],
		[+5, +0, "sea"],
		[+5, +1, "newworld"],
		[+5, +2, "newworld"],
		[+5, +3, "newworld"],
		[+5, +4, "newworld"],
		[+5, +5, "sea"],
		[+6, +1, "sea"],
		[+6, +2, "sea"],
		[+6, +3, "sea"],
		[+6, +4, "sea"],
		[+6, +5, "sea"],
	],
	"decks": {
		"sea": {
			"tiles": [
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				# Extension
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
			],
		},
		"newworld": {
			"hidden": true,
			"shuffled": true,
			"tiles": [
				Terrain.Forest,
				Terrain.Wheat,
				Terrain.Grass,
				Terrain.Mountains,
				Terrain.Mud,
				Terrain.Sea,
			],
			"numbers": [
				6,5,4,3,2,
				8,9,10,11,12,
			],
			"unnumbered": [
				Terrain.Desert,
				Terrain.Sea,
			]
		},
		"land": {
			"shuffled": true,
			"tiles": [
				Terrain.Desert,
				Terrain.Forest,
				Terrain.Forest,
				Terrain.Forest,
				Terrain.Forest,
				Terrain.Wheat,
				Terrain.Wheat,
				Terrain.Wheat,
				Terrain.Wheat,
				Terrain.Grass,
				Terrain.Grass,
				Terrain.Grass,
				Terrain.Grass,
				Terrain.Mountains,
				Terrain.Mountains,
				Terrain.Mountains,
				Terrain.Mud,
				Terrain.Mud,
				Terrain.Mud,
			],
			"numbers": [
				6,6,5,5,4,4,3,3,2,
				8,8,9,9,10,10,11,11,12,
			],
			"unnumbered": [
				Terrain.Desert,
			]
		}
	}
}
