extends Object
class_name ScenarioData

const Terrain = Globals.Terrain
const ResourceType = Globals.ResourceType

static var game = {
	"name": "ClassicExplorer",
	"player_piece_set": {
		"town": 5,
		"city": 4,
		"road": 15,
		#"ship": 0,
		#"wall": 0,
		#"knight_1": 0,
		#"knight_2": 0,
		#"knight_3": 0,
		#"harbour_city": 0,
		#"pirate_ship": 0,
		#"explorer_ship": 0,
		#"settler": 0,
		#"crew": 0,
	},
	"map": [
		# hex-x, hex-y, deck
		[-3, -3, "sea"],
		[-3, -2, "sea"],
		[-3, -1, "sea"],
		[-3, +0, "sea"],
		[-2, -3, "sea"],
		[-2, -2, "land"],
		[-2, -1, "land"],
		[-2, +0, "land"],
		[-2, +1, "sea"],
		[-1, -3, "sea"],
		[-1, -2, "land"],
		[-1, -1, "land"],
		[-1, +0, "land"],
		[-1, +1, "land"],
		[-1, +2, "sea"],
		[+0, -3, "sea"],
		[+0, -2, "land"],
		[+0, -1, "land"],
		[+0, +0, "land"],
		[+0, +1, "land"],
		[+0, +2, "land"],
		[+0, +3, "sea"],
		[+1, -2, "sea"],
		[+1, -1, "land"],
		[+1, +0, "land"],
		[+1, +1, "land"],
		[+1, +2, "land"],
		[+1, +3, "sea"],
		[+2, -1, "sea"],
		[+2, +0, "land"],
		[+2, +1, "land"],
		[+2, +2, "land"],
		[+2, +3, "sea"],
		[+3, +0, "sea"],
		[+3, +1, "sea"],
		[+3, +2, "sea"],
		[+3, +3, "sea"],
		[+4, +0, "sea"],
		[+4, +1, "newworld"],
		[+4, +2, "newworld"],
		[+4, +3, "newworld"],
		[+4, +4, "sea"],
		[+5, +0, "sea"],
		[+5, +1, "newworld"],
		[+5, +2, "newworld"],
		[+5, +3, "newworld"],
		[+5, +4, "newworld"],
		[+5, +5, "sea"],
		[+6, +1, "sea"],
		[+6, +2, "sea"],
		[+6, +3, "sea"],
		[+6, +4, "sea"],
		[+6, +5, "sea"],
	],
	"port_locations": [
		[+0,-3, Hex.Side.Bottom],
		[-2,-3, Hex.Side.BottomRight],
		[-3,-2, Hex.Side.BottomRight],
		[-3,+0, Hex.Side.TopRight],
		[-1,+2, Hex.Side.Top],
		[+1,+3, Hex.Side.Top],
		[+3,+3, Hex.Side.TopLeft],
		[+3,+1, Hex.Side.BottomLeft],
		[+2,-1, Hex.Side.BottomLeft],
	],
	"decks": {
		"sea": {
			"tiles": [
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				# Extension
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
				Terrain.Sea,
			],
			"port_resources": [
				ResourceType.Wood,
				ResourceType.Nothing,
				ResourceType.Brick,
				ResourceType.Nothing,
				ResourceType.Sheep,
				ResourceType.Nothing,
				ResourceType.Grain,
				ResourceType.Nothing,
				ResourceType.Stone,
			],
			"ports_shuffled": true,
		},
		"newworld": {
			"hidden": true,
			"shuffled": true,
			"tiles": [
				Terrain.Forest,
				Terrain.Wheat,
				Terrain.Grass,
				Terrain.Mountains,
				Terrain.Mud,
				Terrain.Sea,
			],
			"numbers": [
				6,5,4,3,2,
				8,9,10,11,12,
			],
			"unnumbered": [
				Terrain.Desert,
				Terrain.Sea,
			]
		},
		"land": {
			"shuffled": true,
			"tiles": [
				Terrain.Desert,
				Terrain.Forest,
				Terrain.Forest,
				Terrain.Forest,
				Terrain.Forest,
				Terrain.Wheat,
				Terrain.Wheat,
				Terrain.Wheat,
				Terrain.Wheat,
				Terrain.Grass,
				Terrain.Grass,
				Terrain.Grass,
				Terrain.Grass,
				Terrain.Mountains,
				Terrain.Mountains,
				Terrain.Mountains,
				Terrain.Mud,
				Terrain.Mud,
				Terrain.Mud,
			],
			"numbers": [
				6,6,5,5,4,4,3,3,2,
				8,8,9,9,10,10,11,11,12,
			],
			"unnumbered": [
				Terrain.Desert,
			],
		}
	}
}
